# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assignment',
            },
        ),
        migrations.CreateModel(
            name='ComponentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_number', models.CharField(max_length=255, null=True)),
                ('component_description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Component Registration',
            },
        ),
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_number', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('pieces', models.IntegerField(default=0)),
                ('cycle_time', models.IntegerField(default=0)),
                ('running_time', models.IntegerField(default=0)),
                ('downtime', models.IntegerField(default=0)),
                ('stops', models.IntegerField(default=0)),
                ('component_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_industry.ComponentRegistration')),
            ],
            options={
                'verbose_name_plural': 'Machine Data',
            },
        ),
        migrations.CreateModel(
            name='MachineRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_number', models.CharField(max_length=255, null=True)),
                ('machine_description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Machine Registration',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Login',
            },
        ),
        migrations.AddField(
            model_name='machineregistration',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_industry.UserLogin'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='component_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_industry.ComponentRegistration'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='machine_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_industry.MachineRegistration'),
        ),
    ]
